# version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: accurack_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: accurack_admin
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: accurack_master
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./backups:/backups
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U accurack_admin -d accurack_master']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - accurack-network

networks:
  accurack-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
